### ISSUE TITLE
Aliases for hostnames/ips

### ISSUE THREAD

**Issue by kdar** [ierror/ssh-permit-a38#2]
Would be nice to have aliases for hostnames/ips. I currently have a bunch of servers that don't have an associated hostname that this would be nice for, but it would also be nice to be able to alias hostnames and use the alias to add/remove users.

**Comment by thornycrackers** [comment]
+1

**Comment by kdar** [comment]
You could edit /etc/hosts and make aliases there instead for the time being. Having ssh-permit-a38 support it is nice when sharing ssh-permit.json with other admins, or so you don't have to type ports with the hostname to grant new users to a host.

**Comment by ierror** [comment]
I think having ssh-permit-a38 support it is the way to go - platform independence wherever possible is a good thing and I like the possibility sharing the JSON DB via a VCS.

Quick and dirty dump of my brain:

- [x] Add optional *hosts.alias* - test with schema version 1.0.0
- [x] increment schema version
- [x] hosts.alias must be unique within the DB
- [x] deny adding alias if a hostname with this value already exists
- [x] deny adding hostname if an alias with this value already exists
- [x] write a helper to resolve hosts.host with an alias or hostname given and replace existing lookups
- [x] write integrations tests

**Comment by ierror** [comment]
- Set an alias "um" for hostname "urlsmash.403.io" 
    `ssh-permit-a38 host urlsmash.403.io alias um`
    
    After this point you can use the alias or the hostname for all host related commands.

- Remove an alias for hostname "urlsmash.403.io" 
    `ssh-permit-a38 host urlsmash.403.io alias`
