### ISSUE TITLE
Reading from ~/.ssh/config file for connection information

### ISSUE THREAD

**Issue by thornycrackers** [ierror/ssh-permit-a38#5]
Hello! First off this is super cool so thanks for putting the effort in to make something like this. It's nice to have a standalone binary for managing server keys. 

The issue that I'm running into is that for syncing multiple hosts, of which there may be different users, ssh-permit starts to break down. For example if I have 5 servers and each one has a different user then when I go to sync I have to manually type in each user for each server plus  hit enter a bunch of times to confirm private key, passphrase, as well as the authorized key files. I've also noticed that adding a host with the same name as a ssh host in my config file is not respected by ssh-permit. 

For example if I have the following in my ~/.ssh/config

```
Host myserver
    ForwardAgent yes
    HostName 192.123.123.123
    Port 12345
    User myuser
```

Then when want to access this host I can use `ssh myserver`. With the advent of having host aliases per host I think it would it would save you having to store more connection information if you have ssh-permit use the host alias to check inside the ~/.ssh/config file. If it does find an entry it could skip asking the questions per host and that way managing multiple servers could really be just running the sync command and maybe having a way to say 'yes' to all.

**Comment by ierror** [comment]
just releases v0.2.0 with SSH Config support - give it a try and let me know if it works for you
